# docker-compose file to execute necessary services
version: '3'

services:
  db:
    build: redis-docker
    volumes:
      - db_volume:/backup
  halocoin:
    build: .
    tty: true
    ports:
      - "127.0.0.1:7001:7001" # Only host should have access to API
      - "7002:7002"
    environment:
      - REDIS_URL=db # Must be equal to service name of redis database (db)
      - HALOCOIN_API_HOST=halocoin # Must be equal to service name of halocoin (halocoin)
      - HALOCOIN_API_PORT=7001
      - HALOCOIN_PEERS_PORT=7002
    depends_on:
      - db
    volumes:
      - halocoin_volume:/data

volumes:
  db_volume:
  halocoin_volume: