version: '3'

services:
  db:
    image: redis
    ports:
      - "6379"
    volumes:
      - data-volume:/data
  halocoin:
    build: .
    tty: true
    ports:
      - "7900:7900"
      - "7899:7899"
    environment: 
      - REDIS_URL=db
    depends_on:
      - db
    volumes:
      - data-volume:/data

volumes:
  data-volume: {}