# docker-compose file to execute necessary services
version: '3'

services:
  db:
    build: redis-docker
    volumes:
      - db_volume:/data
  halocoin:
    build: .
    tty: true
    ports:
      - "127.0.0.1:6899:6899" # Only host should have access to API
      - "6999:6999"
    environment:
      - REDIS_URL=db # Must be equal to service name of redis database (db)
      - HALOCOIN_API_HOST=halocoin # Must be equal to service name of halocoin (halocoin)
      - HALOCOIN_API_PORT=6899
      - HALOCOIN_PEERS_PORT=6900
    depends_on:
      - db
    volumes:
      - halocoin_volume:/data

volumes:
  db_volume:
  halocoin_volume: