version: '3'

services:
  db:
    build: redis-docker
    ports:
      - "6379"
    volumes:
      - ~/.halocoin-docker-redis:/data
  halocoin:
    build: .
    tty: true
    ports:
      - "6899:6899"
      - "6900:6900"
    environment: 
      - REDIS_URL=db
      - HALOCOIN_API_HOST=halocoin
      - HALOCOIN_API_PORT=6899
      - HALOCOIN_PEERS_PORT=6900
    depends_on:
      - db
    volumes:
      - ~/.halocoin-docker:/data